### ISSUE TITLE
ClassCastException while executing `#gc`

### ISSUE THREAD

**Issue by ZacSharp** [ZacSharp/baritone2#2]
## Some information
Operating system: Linux 5.15.0-47-generic
Java version: 1.8.0_342
Minecraft version: 1.12.2 Minecraft 1.12.2
Baritone version: 1.2.15
Other mods (if used): 

## Exception, error or logs
<details><summary>stacktrace</summary><pre>
baritone.api.command.exception.CommandUnhandledException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:143)
	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:127)
	at baritone.command.manager.CommandManager.execute(CommandManager.java:83)
	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:146)
	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:74)
	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:69)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:69)
	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java:1416)
	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java)
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:456)
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:446)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:126)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:607)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:556)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1852)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1165)
	at net.minecraft.client.Minecraft.run(Minecraft.java:439)
	at net.minecraft.client.main.Main.main(Main.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at baritone.command.defaults.GcCommand.execute(GcCommand.java:38)
	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:140)
	... 30 more

</pre></details>
Exception UID: 956213166

## How to reproduce

1. Add
    ```java
    ((String)(Object)5).hashCode();
    ```
    to GcCommand.java
2. Build
3. Install
4. Start the game
5. Join a world or server
6. Run gc

Why? To mark something as a duplicate you need a duplicate.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not messed with any OwO's or UwU's in this issue.
- [x] I have filled in any useful information the autegenerated issue was missing

**Comment by ZacSharp** [comment]
Duplicate of #1

**Comment by ZacSharp** [comment]
Duplicate of #1
